# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000
  host: localhost

test:
  <<: *default
  database: test_db
  username: devuser
  password: 18349276

development:
  <<: *default
  database: joondev_db
  username: devuser
  password: 18349276

production:
  <<: *default
  database: joondev_db
